version: '3'

## Make sure the machine contains java 8 + and Apache Maven installed run this command
##  mvn package && cp target/file-server.jar docker/api && cd docker && docker-compose up --build -d && rm -r api/file-server.jar && cd ..
services:
  file-server-api:
    build:
      dockerfile: Dockerfile
      context: api
    image: v1-file-server:latest
    container_name: v1-file-server-api
    restart: always
    ports:
      - 80:80
    volumes:
      - ~/.local_file_server/files/:/root/.file/
#    command: "java -jar file-server.jar"
